# Generated by Django 5.1.6 on 2025-02-20 16:09

import receipe.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0002_rename_userreceipi_receipi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipiingredient',
            name='unit',
            field=models.CharField(max_length=50, validators=[receipe.validator.validate_unit_measure]),
        ),
    ]
