# Generated by Django 5.1.6 on 2025-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0003_alter_receipiingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipiingredient',
            name='quantity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
